# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x0breplication\"1\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"]\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x13\n\x0blast_update\x18\x03 \x01(\x03\x12\x0f\n\x07version\x18\x04 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"C\n\x0bSyncRequest\x12\x10\n\x08messages\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63ounts\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\".\n\x0cSyncResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xf1\x01\n\x12ReplicationService\x12\x42\n\x0bRequestVote\x12\x18.replication.VoteRequest\x1a\x19.replication.VoteResponse\x12V\n\rAppendEntries\x12!.replication.AppendEntriesRequest\x1a\".replication.AppendEntriesResponse\x12?\n\x08SyncData\x12\x18.replication.SyncRequest\x1a\x19.replication.SyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=34
  _globals['_VOTEREQUEST']._serialized_end=83
  _globals['_VOTERESPONSE']._serialized_start=85
  _globals['_VOTERESPONSE']._serialized_end=135
  _globals['_APPENDENTRIESREQUEST']._serialized_start=137
  _globals['_APPENDENTRIESREQUEST']._serialized_end=230
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=232
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=286
  _globals['_SYNCREQUEST']._serialized_start=288
  _globals['_SYNCREQUEST']._serialized_end=355
  _globals['_SYNCRESPONSE']._serialized_start=357
  _globals['_SYNCRESPONSE']._serialized_end=403
  _globals['_REPLICATIONSERVICE']._serialized_start=406
  _globals['_REPLICATIONSERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
